### PR TITLE
Make sure array of null prototype objects is printable

### LINKED ISSUE #2016: Error: Cannot convert object to primitive value in GHA
**Describe the bug**

When I run github action on my schema it crashes with
Screenshot 2021-09-28 at 16 50 25

Is #1959 available to the github action?

**To Reproduce**

Have a type with default input value like
https://github.com/ertrzyiks/graphql-inspector-issue-2016

Run `kamilkisiela/graphql-inspector` github action on such schema
https://github.com/ertrzyiks/graphql-inspector-issue-2016/pull/1/checks?check_run_id=3736230467

**Expected behavior**

No runtime errors

### PR DESCRIPTION
**Pull request by ertrzyiks**
## Description

Fixes #2016

Follow-up to https://github.com/kamilkisiela/graphql-inspector/pull/2017

Make sure that `safeString` function works with arrays too to prevent failures like 
Screenshot 2021-10-07 at 08 27 56

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Unit tests

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/core/__tests__/utils/string.ts [hunk 1]
```diff
@@ -18,3 +18,14 @@ test('null', () => {
...
+
+test('object', () => {
+  expect(safeString({})).toBe('{}');
+  expect(safeString(Object.create(null, { foo: { value: 42, enumerable: true } }))).toBe('[Object: null prototype] { foo: 42 }');
+});
+
+test('array', () => {
+  expect(safeString(['42', '42'])).toBe("[ '42', '42' ]");
+  expect(safeString([{}])).toBe('[ {} ]');
+  expect(safeString([Object.create(null, { foo: { value: 42, enumerable: true } })])).toBe('[ [Object: null prototype] { foo: 42 } ]');
```
Comment (kamilkisiela) [inline packages/core/__tests__/utils/string.ts:30]:
```suggestion
  expect(safeString([Object.create(null, { foo: { value: 42, enumerable: true } })])).toBe('[ { foo: 42 } ]');
```

File: packages/core/src/utils/string.ts [hunk 2]
```diff
@@ -79,8 +79,5 @@ function wordLetterPairs(str: string) {
 }
 
 export function safeString(obj: any) {
-  if (obj != null && typeof obj.toString === 'function') {
-    return `${obj}`;
-  }
-  return inspect(obj);
+  return inspect(obj).replace(/\[Object\: null prototype\]/g, '');
```
Comment (kamilkisiela) [inline packages/core/src/utils/string.ts:82]:
```suggestion
  return inspect(obj).replace(/\[Object\: null prototype\] /g, '');
```
