### PR TITLE
Apply GitHub Token by default

### LINKED ISSUE #1860: Permission issue on github action
**Describe the bug**

GitHub does not allow incognito access as a pull request from a forked repo is considered dangerous. 
If GitHub tokens are not obtained from secret, actions that can be performed with read privileges become possible. 

**To Reproduce**

pull request.

**Expected behavior**

**Environment:**

- OS:
- `@graphql-inspector/...`:
- `graphql`:
- NodeJS:

**Additional context**

### PR DESCRIPTION
**Pull request by marocchino**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1860

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:
- OS: macOS 11.2.3 (20D91)
- `@graphql-inspector/...`: current master
- NodeJS: 12.7.0

## Checklist:

- [ ] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: packages/action/src/run.ts [hunk 1]
```diff
@@ -50,17 +50,9 @@ export async function run() {
...
-  // env:
-  //   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  //
-  const token = core.getInput('github-token') || process.env.GITHUB_TOKEN;
+  const token = core.getInput('github-token', {required: true})
   const checkName = core.getInput('name') || CHECK_NAME;
 
-  if (!token) {
-    return core.setFailed('Github Token is missing');
-  }
```
Comment (marocchino) [inline packages/action/src/run.ts:62]: If it was possible to not give a token, the above getInput would fail.

**Comment by kamilkisiela** [comment]
Thank you :)
