### PR TITLE
`Diff` identify changes in schema directives

### LINKED ISSUE #2618: Diff does not identify changes in schema directives
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `pnpm generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Diffing a schema does not identify changes in schema directives, which can still be an important change. For example:

```graphql
type Alpha {
  id: ID!
  title: String
}
```

The above should register a change when the following transformation appears:

```graphql
type Alpha {
  id: ID!
  title: String @external
}
```

### PR DESCRIPTION
**Pull request by TuvalSimha**
Closes #2618 

- [x]  SCHEMA = 'SCHEMA',
- [x]   SCALAR = 'SCALAR',
- [x]   OBJECT = 'OBJECT',
- [x]   FIELD_DEFINITION = 'FIELD_DEFINITION',
- [x]   ARGUMENT_DEFINITION = 'ARGUMENT_DEFINITION',
- [x]   INTERFACE = 'INTERFACE',
- [x]   UNION = 'UNION',
- [x]   ENUM = 'ENUM',
- [x]   ENUM_VALUE = 'ENUM_VALUE',
- [x]   INPUT_OBJECT = 'INPUT_OBJECT',
- [x]   INPUT_FIELD_DEFINITION = 'INPUT_FIELD_DEFINITION',

### CODE REVIEW

**Comment by TuvalSimha** [comment]
What about `/** Request Definitions */`?

File: packages/core/src/diff/changes/change.ts [hunk 1]
```diff
@@ -368,6 +387,32 @@ export type FieldTypeChangedChange = {
   };
 };
 
+export type DirectiveUsageAddedChange = {
```
Comment (dotansimha) [inline packages/core/src/diff/changes/change.ts:390]: this one is in use?

File: packages/core/src/diff/changes/change.ts [hunk 2]
```diff
@@ -368,6 +387,32 @@ export type FieldTypeChangedChange = {
...
+  type: ChangeType.DirectiveUsageAdded;
+  meta: {};
+};
+
+export type DirectiveUsageRemovedChange = {
```
Comment (dotansimha) [inline packages/core/src/diff/changes/change.ts:395]: this one is in use?

File: packages/core/src/diff/changes/directive-usage.ts [hunk 3]
```diff
@@ -0,0 +1,206 @@
...
+}
+
+export function directiveUsageBuildUnionMemberAddedMessageFromMeta(
+  args: DirectiveUsageUnionMemberAddedChange,
+) {
+  return {
+    criticality: {
+      level: CriticalityLevel.Dangerous,
+      reason:
+        'Adding a union member to a union can cause existing queries that use this union member in a fragment spread to error.',
```
Comment (dotansimha) [inline packages/core/src/diff/changes/directive-usage.ts:51]: This should probably be something else?

File: packages/core/src/diff/changes/directive-usage.ts [hunk 4]
```diff
@@ -0,0 +1,206 @@
...
+    },
+    type: ChangeType.DirectiveUsageUnionMemberAdded,
+    message: `Directive '${args.meta.addedUnionMemberTypeName}' was added to Union type '${args.meta.unionName}'`,
```
Comment (dotansimha) [inline packages/core/src/diff/changes/directive-usage.ts:54]: Not sure if it should be `added to Union` or `added on Union`. 
Also, I think it's better to just `union` and not `Union` here.

File: packages/core/src/diff/changes/directive-usage.ts [hunk 5]
```diff
@@ -0,0 +1,206 @@
...
+  };
+}
+
+export function directiveUsageRemoved(
+  directive: ConstDirectiveNode,
+  path: string,
+): Change<ChangeType.DirectiveUsageRemoved> {
+  return {
+    criticality: {
+      level: CriticalityLevel.Dangerous,
```
Comment (dotansimha) [inline packages/core/src/diff/changes/directive-usage.ts:35]: No `reason`?

File: packages/core/src/diff/changes/directive-usage.ts [hunk 6]
```diff
@@ -0,0 +1,206 @@
...
+  CriticalityLevel,
+  DirectiveUsageEnumAddedChange,
+  DirectiveUsageEnumRemovedChange,
+  DirectiveUsageEnumValueAddedChange,
+  DirectiveUsageEnumValueRemovedChange,
+  DirectiveUsageUnionMemberAddedChange,
+  DirectiveUsageUnionMemberRemovedChange,
+} from './change.js';
+
+export function directiveUsageAdded(
```
Comment (dotansimha) [inline packages/core/src/diff/changes/directive-usage.ts:14]: Are we using this one? I think it was from the initial work we did?

File: packages/core/src/diff/changes/directive-usage.ts [hunk 7]
```diff
@@ -0,0 +1,206 @@
...
+}
+
+export function directiveUsageBuildUnionMemberRemovedMessageFromMeta(
+  args: DirectiveUsageUnionMemberRemovedChange,
+) {
+  return {
+    criticality: {
+      level: CriticalityLevel.Dangerous,
+      reason:
+        'Removing a union member from a union can cause existing queries that use this union member in a fragment spread to error.',
```
Comment (dotansimha) [inline packages/core/src/diff/changes/directive-usage.ts:80]: reason is not up to date

File: packages/core/src/diff/changes/directive-usage.ts [hunk 8]
```diff
@@ -0,0 +1,206 @@
...
+    },
+  });
+}
+
+export function directiveUsageEnumAddedFromMeta(args: DirectiveUsageEnumAddedChange) {
+  return {
+    type: ChangeType.DirectiveUsageEnumAdded,
+    criticality: {
+      level: CriticalityLevel.Dangerous,
+      reason: `Directive '${args.meta.addedDirectiveName}' was added to Enum '${args.meta.enumName}'`,
```
Comment (dotansimha) [inline packages/core/src/diff/changes/directive-usage.ts:107]: Reason should not be the same as the message, right? 
Also, `Enum` -> `enum` (same for all other keywords)

File: packages/core/src/diff/changes/directive-usage.ts [hunk 9]
```diff
@@ -0,0 +1,206 @@
...
+    },
+  });
+}
+
+export function directiveUsageEnumRemovedFromMeta(args: DirectiveUsageEnumRemovedChange) {
+  return {
+    type: ChangeType.DirectiveUsageEnumRemoved,
+    criticality: {
+      level: CriticalityLevel.Dangerous,
+      reason: `Directive '${args.meta.removedDirectiveName}' was removed from Enum '${args.meta.enumName}'`,
```
Comment (dotansimha) [inline packages/core/src/diff/changes/directive-usage.ts:133]: Reason should not be the same as the message, right?
Also, Enum -> enum (same for all other keywords)

File: packages/core/src/diff/changes/field.ts [hunk 10]
```diff
@@ -434,3 +437,65 @@ export function fieldArgumentRemoved(
...
+  return `Directive '${args.removedDirectiveName}' was removed from Interface type '${args.interfaceName}'`;
+}
+
+export function fieldInterfaceRemovedFromMeta(args: DirectiveUsageInterfaceRemovedChange) {
+  return {
+    type: ChangeType.DirectiveUsageInterfaceRemoved,
+    criticality: {
+      level: CriticalityLevel.Breaking,
+      reason:
+        'Removing a directive from an interface type can cause existing queries that use this directive to error.',
```
Comment (dotansimha) [inline packages/core/src/diff/changes/field.ts:451]: Not clear enough, let's think together what should be the reason here.

File: packages/core/__tests__/diff/directive-usage.test.ts [hunk 11]
```diff
@@ -0,0 +1,501 @@
...
+      console.log('change', change);
+
+      expect(changes.length).toEqual(1);
+      expect(change.criticality.level).toEqual(CriticalityLevel.Breaking);
+      expect(change.type).toEqual('DIRECTIVE_USAGE_FIELD_REMOVED');
+      expect(change.message).toEqual("Directive 'external' was removed from Input Object 'a'");
+    });
+  });
+
+  describe('scalar-field-level directives', () => {
```
Comment (dotansimha) [inline packages/core/__tests__/diff/directive-usage.test.ts:370]: `scalar-level` *

File: packages/core/src/diff/input.ts [hunk 12]
```diff
@@ -21,6 +25,7 @@ export function changesInInputObject(
 
   compareLists(Object.values(oldFields), Object.values(newFields), {
     onAdded(field) {
+      console.log('field', field);
```
Comment (dotansimha) [inline packages/core/src/diff/input.ts:28]: remove

File: packages/core/__tests__/diff/directive-usage.test.ts [hunk 13]
```diff
@@ -0,0 +1,501 @@
...
+      const b = buildSchema(/* GraphQL */ `
+        directive @external on INPUT_FIELD_DEFINITION
+        input Foo {
+          a: String @external
+          b: String
+        }
+      `);
+
+      const changes = await diff(a, b);
+      console.log('changes', changes);
```
Comment (dotansimha) [inline packages/core/__tests__/diff/directive-usage.test.ts:333]: remove

File: packages/core/__tests__/diff/directive-usage.test.ts [hunk 14]
```diff
@@ -0,0 +1,501 @@
...
+      const change = findFirstChangeByPath(changes, 'a.external');
+      console.log('change', change);
```
Comment (dotansimha) [inline packages/core/__tests__/diff/directive-usage.test.ts:335]: remove

File: packages/core/__tests__/diff/directive-usage.test.ts [hunk 15]
```diff
@@ -0,0 +1,501 @@
...
+      const b = buildSchema(/* GraphQL */ `
+        directive @external on INPUT_FIELD_DEFINITION
+        input Foo {
+          a: String
+          b: String
+        }
+      `);
+
+      const changes = await diff(a, b);
+      console.log('changes', changes);
```
Comment (dotansimha) [inline packages/core/__tests__/diff/directive-usage.test.ts:359]: remove

File: packages/core/__tests__/diff/directive-usage.test.ts [hunk 16]
```diff
@@ -0,0 +1,501 @@
...
+      const change = findFirstChangeByPath(changes, 'a.external');
+      console.log('change', change);
```
Comment (dotansimha) [inline packages/core/__tests__/diff/directive-usage.test.ts:361]: remove

File: packages/core/__tests__/diff/directive-usage.test.ts [hunk 17]
```diff
@@ -0,0 +1,501 @@
...
+      `);
+      const b = buildSchema(/* GraphQL */ `
+        directive @external on OBJECT
+        type Foo {
+          a: String
+        }
+      `);
+
+      const changes = await diff(a, b);
+      console.log('changes', changes);
```
Comment (dotansimha) [inline packages/core/__tests__/diff/directive-usage.test.ts:447]: remove

File: packages/core/src/diff/input.ts [hunk 18]
```diff
@@ -30,6 +35,15 @@ export function changesInInputObject(
       changesInInputField(oldInput, field.oldVersion, field.newVersion, addChange);
     },
   });
+
+  compareLists(oldInput.astNode?.directives || [], newInput.astNode?.directives || [], {
+    onAdded(diractive) {
+      addChange(inputObjectAdded(newInput, diractive));
```
Comment (dotansimha) [inline packages/core/src/diff/input.ts:41]: should this be something else? or is it just me being confused by the name `inputObjectAdded` and `inputObjectRemoved`?

**Review by dotansimha — COMMENTED** [review]
Great progress. I think the following are still missing:
- Compare and handle changes in arguments (and values) that are set on a directive usage. I assume you can use the same function to handle arguments as in field-arguments?
- There should be an option to configure this rule to maybe ignore some specific directives? and the default behavior should ignore some specific directives, for example, Federation v1/v2 directives and Fusion directives. 
- Some directives will need to have special handling regarding the level of danger - like `@oneOf` (when added = breaking change, when removed = safe) and `@deprecated` (should always be considered safe, because it's just metadata).

**Comment by dotansimha** [comment]
I think we can allow users to configure it with an object like that: 

```ts
type Level = 'safe' | 'breaking' | '...';
type DirectiveUsageConfig = Record<string, false, Level | {
  removed?: Level
  added?: Level
}>
```

```ts
{
   'oneOf': { // safe when removed, breaking when added
      removed: 'safe',
      added: 'breaking'
   },
   'deprecated': 'safe', // always treat as safe
   'key': false // ignore this directice
}
```

@n1ru4l @kamilkisiela thoughts?

**Comment by n1ru4l** [comment]
The semantics of `@oneOf` are pretty clear, so why would we allow overwriting the "true" behavior in order to be wrong? I think it should be hard-coded instead of generic for all directives. Directives can have different behaviors based on arguments (even different argument combinations). Having a flexible solution that pleases many might backfire here.

**Comment by dotansimha** [comment]
> The semantics of `@oneOf` are pretty clear, so why would we allow overwriting the "true" behavior in order to be wrong? I think it should be hard-coded instead of generic for all directives. Directives can have different behaviors based on arguments (even different argument combinations). Having a flexible solution that pleases many might backfire here.

I fully agree, I gave it as a (bad) example for configuration - this will probably be an internal configuration, that can be extended (with more directives) by the user (without overriding `oneOf`)

File: packages/core/src/diff/input.ts (hunk 18 above)
Comment (dotansimha) [reply packages/core/src/diff/input.ts:41]: Also, `directive` instead of `diractive`

File: packages/core/src/diff/changes/directive-usage.ts [hunk 19]
```diff
@@ -0,0 +1,874 @@
...
+        );
+      }
+      break;
+  }
+
+  throw new Error(`Unhandled case: ${changeCase}`);
+}
+
+interface DirectiveUsageAddedController {
+  case:
```
Comment (dotansimha) [inline packages/core/src/diff/changes/directive-usage.ts:241]: This could leverage TypeScript in a better way. 
You can build this as a map and then infer the expected type. 
Also, you can use `Kind` of GraphQL for that. 

Check this: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgaWAOwCYBo4HEoCGYAFgIoAyAomgK4gAqAnmAKY75FnkCqawEaJq3aESFAPIAjAFYsAxjCFs4AQQDK9AHIQMLOAF84AMygQQcAOQBzUcQCOAGwsBuAFCuYzPakz0IKqCs6FjR4AF5EVzhouABtHwwAOkpNbgBZAH16AE0ABUoMgBFKADEASU0y+jLxTQBdAC48WwpqOiUsKJj49CTuStqsvILi8srq2sbmzgpefkEvTv13Ixo0BXm4YABncSMEgB4EuBYADxgQjG24AGsWRggjFF6-AKCQEJgcADUT88vrkgCNsYNpdAB+JrqLQ6PQAHzgtAcDgMAD4ABQ3XpNBI4ABuBAcNBYTW+AEomgSiXods9fP5AsFQj1MHVIjE4FAWDAaFA0HAqcTEsDQbDwYksZg4GEZbdem5lq5VusYJsMBA1GZucR0FYjr0-hdMNc7g8nglXoyPqFUXBMdi6dgBYTiTiXgz3p8WRg6mT2TEAPQBuAACRYXLgAHc9HICPyrNy4HIIBAUZ5WFs0EZwyE5HoutFgE90Ts9gl0QlkqlMjl8kVShUqjVNPiXSwyX6EAWOXAg6Gczh0NtgLo4DBiAR4AAiItTnDjvRTwUsKdwAhWz5ba66C4KFgYNfXDhiKi0BhebuGFgObY04ul-a9Cu9RL9ZtDOujRsTFvO6kd-0e17YMwy5Qc0GHUdx0nOAZyMOcx2IRdl1XddPVCLc4B3eQLgPYFphPOYBCUS9XEVPt6B1a5aSpEc1ylEBJzkJDtlcdVNQ+cddWfTAq3SD8RgbcZmxwNAWEjAiuDac9WHRJA0AID4minC4QQQ5dtiaBB9H0Ds3FcPsyieaMxygRgxwgOBGJgZiTjPOUpRgSzti1Li0CsE4b2UYB4CMAhgBvNiNVcnV3J4pIUn42tBLGJtalE8TJIkGQcKUOTEUUklYNUmAEKMYBryuLT9BwXSyX0oA

**Review by dotansimha — APPROVED** [review]
LGTM. Let's wait for @n1ru4l / @kamilkisiela to review before merging.
Also, you need to add a `changeset` file (`minor`).

**Comment by dotansimha** [comment]
Also, CI fails

File: packages/core/__tests__/diff/directive-usage.test.ts [hunk 20]
```diff
@@ -0,0 +1,719 @@
...
+      `);
+
+      const changes = await diff(a, b);
+      const change = findFirstChangeByPath(changes, 'Foo.a.external');
+
+      expect(changes.length).toEqual(1);
+      expect(change.criticality.level).toEqual(CriticalityLevel.Dangerous);
+      expect(change.type).toEqual('DIRECTIVE_USAGE_ARGUMENT_DEFINITION_ADDED');
+      expect(change.message).toEqual("Directive 'external' was added to argument 'a'");
+    });
```
Comment (n1ru4l) [inline packages/core/__tests__/diff/directive-usage.test.ts:460]: Isn't this an input field and not a argument definition?
